name: Nightly Tests

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

env:
  MIX_ENV: test

jobs:
  extended-compatibility:
    name: Extended Compatibility Matrix
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest versions
          - elixir: '1.16'
            otp: '26'
          - elixir: '1.16'
            otp: '25'
          # Previous versions
          - elixir: '1.15'
            otp: '26'
          - elixir: '1.15'
            otp: '25'
          - elixir: '1.15'
            otp: '24'
          - elixir: '1.14'
            otp: '25'
          - elixir: '1.14'
            otp: '24'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: nightly-${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          nightly-${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-
          nightly-${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile project
      run: mix compile --warnings-as-errors

    - name: Run comprehensive test suite
      run: mix test.numberf_all --slowest 30

  stress-tests:
    name: Stress Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'
        otp-version: '26'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: stress-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          stress-${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile project
      run: mix compile

    - name: Run stress tests with high load
      run: |
        # Run tests multiple times to catch intermittent issues
        for i in {1..5}; do
          echo "Stress test iteration $i"
          mix test --only performance --timeout 600000
          mix test test/concurrency/ --timeout 600000
        done

    - name: Memory stress test
      run: |
        # Run memory-intensive tests
        mix test test/performance/ --timeout 900000

  long-running-tests:
    name: Long Running Tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'
        otp-version: '26'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: longrun-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          longrun-${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile project
      run: mix compile

    - name: Run extended property-based tests
      run: |
        # Run property tests with more iterations
        MIX_ENV=test mix test --only property --timeout 3600000

    - name: Run extended benchmark tests
      run: |
        # Run comprehensive benchmarks
        mix test --only benchmark --timeout 3600000

  memory-leak-detection:
    name: Memory Leak Detection
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'
        otp-version: '26'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: memory-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          memory-${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile project
      run: mix compile

    - name: Run memory tests
      run: mix test test/number_f/memory_test.exs --timeout 1800000

    - name: Check for memory leaks in long-running operations
      run: |
        # Run specific tests that might reveal memory leaks
        mix test test/performance/ --timeout 1800000

  cross-platform-tests:
    name: Cross Platform Tests
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'
        otp-version: '26'

    - name: Cache dependencies (Unix)
      if: runner.os != 'Windows'
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: cross-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          cross-${{ runner.os }}-mix-

    - name: Cache dependencies (Windows)
      if: runner.os == 'Windows'
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: cross-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          cross-${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile project
      run: mix compile --warnings-as-errors

    - name: Run core tests
      run: mix test.numberf_fast

    - name: Run platform-specific tests
      run: |
        # Test internationalization features that might behave differently on different platforms
        mix test test/number_f/i18n_test.exs
        mix test test/focused/internationalization_edge_cases_test.exs

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'
        otp-version: '26'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: security-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          security-${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Run security audit
      run: mix deps.audit

    - name: Check for known vulnerabilities
      run: |
        # Additional security checks
        mix deps.tree
        mix deps.unlock --check-unused

  notification:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [extended-compatibility, stress-tests, long-running-tests, memory-leak-detection, cross-platform-tests, security-audit]
    if: always()
    
    steps:
    - name: Notify on failure
      if: contains(needs.*.result, 'failure')
      run: |
        echo "Nightly tests failed. Check the logs for details."
        echo "Failed jobs:"
        echo "Extended Compatibility: ${{ needs.extended-compatibility.result }}"
        echo "Stress Tests: ${{ needs.stress-tests.result }}"
        echo "Long Running Tests: ${{ needs.long-running-tests.result }}"
        echo "Memory Leak Detection: ${{ needs.memory-leak-detection.result }}"
        echo "Cross Platform Tests: ${{ needs.cross-platform-tests.result }}"
        echo "Security Audit: ${{ needs.security-audit.result }}"

    - name: Notify on success
      if: ${{ !contains(needs.*.result, 'failure') }}
      run: |
        echo "All nightly tests passed successfully!"
